import { css } from 'lit';

// These are "JS-ified" versions of the CSS files from the Material Components Web library & Fonts.
// These are required to use the Material Components Web components in Lit, as the regular CSS files
// are hidden from the web components.
// These are generated by the `css-to-js` script in the `build-tools` directory.
import _material_components_web_min_css from './style_scripts/material_components_web_min_css';
import _MaterialIcons_Regular_css from './style_scripts/MaterialIcons_Regular_css';

export const styles = css`
  /* Material Components Web Component Library */
  ${_material_components_web_min_css}

  /* Fonts */
  ${_MaterialIcons_Regular_css}

  /* These are our custom styles, applied after the materials-components CSS. */
  
  /* reset */
  html,
  body {
    width: 100%;
    height: 100%;
  }
  
  body {
    margin: 0;
    padding: 0;
    font-size: 16px;
    font-family: sans-serif;
  }
  
  *, *::before, *::after {
    box-sizing: border-box;
  }
  
  h1, h2, h3, h4, h5, h6, p {
    margin-top: 0;
  }
  
  /* font size adapts to the size of the site */
  .responsive-font-size {
    font-size: calc([minimum size] + ([maximum size] - [minimum size]) * ((100vw - [minimum viewport width]) / ([maximum viewport width] - [minimum viewport width])));
    font-size: clamp(min, viewport-width-unit, max); /* alternative */
  }
  
  .frosted-glass-container {
      background-color: rgba(255, 255, 255, .15);
      backdrop-filter: blur(5px);
  }

  .wrapper {
    /*
    --max-width: 960px;
    --min-gap: 25px;
    --side-gap: calc((100vw - min(var(--max-width), calc(100vw - (var(--min-gap) * 2)))) / 2);
    padding-left: var(--side-gap);
    padding-right: var(--side-gap);
    */
    padding: 15px calc((100vw - min(900px, calc(100vw - 50px))) / 2); 
  }
  /* alternative to the above:
  main {
    padding: 15px calc((100vw - min(900px, calc(100vw - 50px))) / 2);
  }
  */

  * {
    font-family: system-ui, Roboto, sans-serif;
    --mdc-typography-button-font-size: .75rem;
    --mdc-outlined-button-container-height: 30px;
    --mdc-typography-subtitle1-font-size: .85rem;

    --mdc-theme-primary: midnightblue;
  }

  /* Adjust size of notch to solve label clipping problem on mdc-text-fields*/
  .mdc-text-field label.mdc-floating-label {
    padding-right: 20px;
  }
`